# pod-reader-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader-role
rules:
- apiGroups: [""] # "" indicates the core API group (pods, services)
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
